[package]
name = "self-signed-quic"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
quinn = "0.11.8"
quinn-proto = "0.11.12"
rcgen = "0.13.2"
tokio = { version = "1.45.1", features = ["full"] }
